/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mo100
 */
public class ClientFrame extends javax.swing.JFrame {
    private Bank bank;
    
    /**
     * Creates new form ClientFrame
     */
    public ClientFrame(Bank bank) {
        setResizable(false);
        initComponents();
        this.bank = bank;
        listClients.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientPanel = new javax.swing.JPanel();
        findUser = new javax.swing.JButton();
        addUser = new javax.swing.JButton();
        listUser = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        panelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listClients = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        findUser.setText("Find");
        findUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findUserActionPerformed(evt);
            }
        });

        addUser.setText("Create");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });

        listUser.setText("List");
        listUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUserActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        panelTitle.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        panelTitle.setText("Clients Actions");

        listClients.setColumns(20);
        listClients.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        listClients.setRows(5);
        jScrollPane1.setViewportView(listClients);

        javax.swing.GroupLayout ClientPanelLayout = new javax.swing.GroupLayout(ClientPanel);
        ClientPanel.setLayout(ClientPanelLayout);
        ClientPanelLayout.setHorizontalGroup(
            ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit)
                    .addComponent(listUser)
                    .addComponent(addUser)
                    .addComponent(findUser))
                .addGap(51, 51, 51)
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientPanelLayout.createSequentialGroup()
                        .addComponent(panelTitle)
                        .addGap(82, 82, 82)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        ClientPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addUser, exit, findUser, listUser});

        ClientPanelLayout.setVerticalGroup(
            ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientPanelLayout.createSequentialGroup()
                .addGroup(ClientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClientPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(findUser)
                        .addGap(18, 18, 18)
                        .addComponent(addUser)
                        .addGap(18, 18, 18)
                        .addComponent(listUser)
                        .addGap(57, 57, 57)
                        .addComponent(exit))
                    .addGroup(ClientPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelTitle)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        ClientPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addUser, exit, findUser, listUser});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ClientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        Runtime.getRuntime().halt(0);
    }//GEN-LAST:event_exitActionPerformed

    private void listUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUserActionPerformed
        // TODO add your handling code here:
        //bank.showClients();
        listClients.setText(bank.showClients());
        listClients.setVisible(true);
    }//GEN-LAST:event_listUserActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        // TODO add your handling code here
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewClientFrame(bank).setVisible(true);
            }
        });
    }//GEN-LAST:event_addUserActionPerformed

    private void findUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findUserActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindClientFrame(bank).setVisible(true);
            }
        });
    }//GEN-LAST:event_findUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClientPanel;
    private javax.swing.JButton addUser;
    private javax.swing.JButton exit;
    private javax.swing.JButton findUser;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea listClients;
    private javax.swing.JButton listUser;
    private javax.swing.JLabel panelTitle;
    // End of variables declaration//GEN-END:variables
}
